---
- name: Create Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ influxdb_data_directory }}"
    - "{{ telegraf_config_directory }}"

- name: influxdb
  docker_container:
    name: influxdb
    image: influxdb
    pull: true
    volumes:
      - "{{ influxdb_data_directory }}:/var/lib/influxdb:rw"
      - "8086:8086"
    restart_policy: unless-stopped
    memory: 1g

- name: Template telegraf.conf
  template:
    src: telegraf.conf
    dest: "{{ telegraf_config_directory }}/telegraf.conf"

- name: telegraf
  docker_container:
    name: telegraf
    image: telegraf
    pull: true
    volumes:
      - "{{ telegraf_config_directory }}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
    restart_policy: unless-stopped
    memory: 1g

