---
pipeline:
  syntax_check:
    image: plugins/ansible:3
    settings:
      playbook: nas.yml
      galaxy: requirements.yml
      inventory: tests/inventories/integration_testing/inventory
      syntax_check: true

