---
piwigo_enabled: false
piwigo_available_externally: "false"

# directories
piwigo_config_directory: "{{ docker_home }}/piwigo/config"
piwigo_data_directory: "{{ docker_home }}/piwigo/data"
piwigo_photos: "{{ photos_root }}"

# uid / gid
piwigo_user_id: "1000"
piwigo_group_id: "1000"

piwigo_photos_permission: "rw"

# network
piwigo_hostname: "piwigo"
piwigo_port: "16923"

# specs
piwigo_memory: "1g"
piwigo_mysql_memory: "1g"

piwigo_version: "docker"
