---
# enable or disable the application
example_app_enabled: false
example_app_available_externally: "false"

# directories
example_app_config_directory: "{{ docker_home }}/example_app/config"
example_app_logs: "{{ docker_home }}/example_app/logs"
example_app_share_directory: "{{ example_share_root }}"


# uid / gid
example_app_user_id: "0"
example_app_group_id: "0"

# network
example_app_hostname: "example_app"
example_app_port: "12345"

# specs
example_app_memory: "1g"
