# This is a basic workflow to help you get started with Actions

name: Integration

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible

      - name: Run playbook
        run: ansible-playbook -i inventories/sample/inventory nas.yml