---
name: Integration

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        shell: bash
        run: "tests/github-test-matrix.sh"

  test:
    name: "Test ${{ matrix.role }}"
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
        matrix:
            role: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Dump env context
        id: env_context_step
        run: echo '${{ toJSON(env) }}'
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --base-config ../../tests/molecule/base.yml
          molecule_command: test
          molecule_working_dir: /github/workspace/${{ matrix.role }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
